// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlFAtt5z_CAeAJ9Iw0QbWx_HIlQVJS33M',
    appId: '1:119681251091:web:ee0f8b79dc97ae3238cce6',
    messagingSenderId: '119681251091',
    projectId: 'chat-app-2d6d6',
    authDomain: 'chat-app-2d6d6.firebaseapp.com',
    storageBucket: 'chat-app-2d6d6.firebasestorage.app',
    measurementId: 'G-KSZXHDM3MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzKssKr_wyCYXxWnE-JNLWLlpT6-L6wYA',
    appId: '1:119681251091:android:5aded1d73bba806238cce6',
    messagingSenderId: '119681251091',
    projectId: 'chat-app-2d6d6',
    storageBucket: 'chat-app-2d6d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8LHj_OpmQhQFF5xqFy6j-OXvNBRcmAq4',
    appId: '1:119681251091:ios:4be5cd14996f1d3138cce6',
    messagingSenderId: '119681251091',
    projectId: 'chat-app-2d6d6',
    storageBucket: 'chat-app-2d6d6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8LHj_OpmQhQFF5xqFy6j-OXvNBRcmAq4',
    appId: '1:119681251091:ios:4be5cd14996f1d3138cce6',
    messagingSenderId: '119681251091',
    projectId: 'chat-app-2d6d6',
    storageBucket: 'chat-app-2d6d6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlFAtt5z_CAeAJ9Iw0QbWx_HIlQVJS33M',
    appId: '1:119681251091:web:cddc811842f41d4238cce6',
    messagingSenderId: '119681251091',
    projectId: 'chat-app-2d6d6',
    authDomain: 'chat-app-2d6d6.firebaseapp.com',
    storageBucket: 'chat-app-2d6d6.firebasestorage.app',
    measurementId: 'G-Y8VXR19MHJ',
  );
}
